#!/bin/bash
clear

echo "Declaring Variables"

OsmFileXML=$1
OsmFileCSV="$1.csv"

maxLat=$2
minLat=$3
maxLon=$4
minLon=$5

OSMAPI="https://api.openstreetmap.org/api/0.6/map?bbox=$5,$3,$4,$2"

echo "Constructed URL: "
echo $OSMAPI

wget -O $1 $OSMAPI

echo "Retrieval finished"

java -jar SaxonHE9-7-0-15J/saxon9he.jar -xsl:Templates/osm-ways-csv.xsl -s:$OsmFileXML -o:$OsmFileCSV

rm $OsmFileXML

mv $OsmFileCSV Output\
